[project]
name = "staking-contract"
authors = ["Hammed Yakub <hamsohood@gmail.com>"]
description = "A Clarity smart contract for staking tokens, earning rewards, and applying penalties for early withdrawals."
license = "MIT"
telemetry = false

[contracts.staking]
path = "contracts/staking.clar"
depends_on = []

[repl]
costs_version = 1

[[accounts]]
name = "deployer"
balance = 100000000000

[[accounts]]
name = "wallet_1"
balance = 50000000000

[[accounts]]
name = "wallet_2"
balance = 50000000000
