[project]
name = "staking-contract"
authors = ["Hammed Yakub <hamsohood@gmail.com>"]
description = "Staking contract with SIP-010 fungible token integration"
telemetry = true
requirements = []

[contracts.staking]
path = "contracts/staking.clar"
depends_on = ["ft-trait"]

[contracts.ft-trait]
path = "contracts/ft-trait.clar"
